services:
  # Serviço para o seu backend Node.js
  backend:
    env_file:
      - .env
    build: . # Indica onde está o Dockerfile do backend
    ports:
      - "3000:3000" # Mapeia a porta 3000 do host para a porta 3000 do container
    volumes:
      - node_modules:/app/node_modules # Volume nomeado para dependências
    environment:
      # Variáveis de ambiente para o backend
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      CALLBACK_URL: ${CALLBACK_URL}
      PORT: ${PORT}
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy

  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:13-alpine # Usa uma imagem oficial do PostgreSQL
    environment:
      # Variáveis de ambiente para o PostgreSQL
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Mapeia a porta 5432 do host para a porta 5432 do container
    volumes:
      - db_data_prod:/var/lib/postgresql/data # Volume persistente único
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data_prod: # Volume nomeado para o banco
  node_modules: # Volume para node_modules
