services:
  # Serviço para o seu backend Node.js
  backend:
    env_file:
      - .env
    build: . # Indica onde está o Dockerfile do backend
    ports:
      - "3000:3000" # Mapeia a porta 3000 do host para a porta 3000 do container
    volumes:
      - .:/app # Monta o volume para desenvolvimento (mudanças no código refletem no container)
      - node_modules:/app/node_modules # Usa volume nomeado para node_modules no container
    environment:
      # Variáveis de ambiente para o backend
      DATABASE_URL: postgres://user:postgres@db:5432/mydatabase
      JWT_SECRET: ${JWT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      CALLBACK_URL: ${CALLBACK_URL}
      PORT: ${PORT}
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy

  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:13-alpine # Usa uma imagem oficial do PostgreSQL
    environment:
      # Variáveis de ambiente para o PostgreSQL
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Mapeia a porta 5432 do host para a porta 5432 do container
    volumes:
      - db_data:/var/lib/postgresql/data # Volume persistente para os dados do banco
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydatabase || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

volumes:
  db_data: # Define o volume para o banco de dados
  node_modules:
